### ISSUE TITLE
Download files Same-Origin problem

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#130]
Nowadays browsers try to protect users so they (browsers) don't download any documents if their (documents) origin isn't the same as an application origin. Now we face with this because the app is recieved from `https://portal-dev.carsnoop.com/` but the documents are got from something like `www.s3-21234....com` so browsers don't download them but open them on another tab. I know only one way how to fix it - move both services (app, documents) on the one domain

**Comment by Ryanb58** [comment]
CORS ended up being already enabled on the bucket, but only for GET and PUT methods. I went ahead and enabled it for POST just to be safe using the config below.

CORS config on bucket.
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]
```

As I was researching, I found discussion on stack overflow about the boto3 client taking on the region in which the LAMBDA is executed within. Which is very strange because S3 buckets are "supposedly" region free. So based on some information I got from that post I went ahead and specified a default region in code to be `us-east-2` in the lambda function that generates the pre-signed URLs.

I can't be sure what I've done will fix the issue, so you'll need to check it and verify.

If you still have this issue. Please post some screenshots of your chrome debugger on the network tab.

**Comment by k-tratseuski** [comment]
@Ryanb58 I think the problem is not in region. We need somehow to receive pre-signed url with such domain `portal-dev.carsnoop.com`. I'm not sure but we might need to configure CloudFront somehow to have something like this `files.portal-dev.carsnoop.com/...`. Currently we receive the link with such host `carsnoop-files.s3.amazonaws.com`.

Maybe [this](https://stackoverflow.com/questions/53128521/aws-get-pre-signed-url-with-custom-domain) one could help somehow

**Comment by Skalapendra69** [comment]
https://caniuse.com/mdn-html_elements_a_download - see notes section here

**Comment by Ryanb58** [comment]
I enabled CORS on the bucket so we wouldn't have to proxy the domains as that would cost a bandwidth fee through cloudfront.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html

By enabling CORS on the buckets, we are explicitly granting cross domain access for any of the s3 bucket URLs.

I suspect you are still experiencing this issue because the endpoints being used might point towards a different S3 bucket than the one I was modifying. I'll add the CORS policy to the following buckets. Please try again.

- carsnoop
- carsnoop-documents
- carsnoop-files

To verify the S3 configuration(server side), use the following jsfiddle and replace the `src` attribute with a presigned url you get from the server.

**Comment by k-tratseuski** [comment]
@Ryanb58 Seems that what you've done is not that we need since we need to have the same host name for app and file links and CORS is not helping to achieve this.
1) With current implementation all the files are opening in the extra tab, since browsers disabled direct downloading for such cases (with different hosts)
But we want not to open file in the extra tab, we want to download it straightaway. This will only work for file links, where the host is the same as the app host.

2) For getting presigned urls `FE` triggers `getDocumentUrl` from `databaseFunctions` which simply proxies the request to `getFileDownloadUrl` from `fileFunctions`

**Comment by k-tratseuski** [comment]
Discussed with @billypilgrim88 that for now is ok to open files in the new tab, so not relevant for now
