### ISSUE TITLE
Go-Live Checklist

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#186]
**1. Create production database - DONE**
2. Create production S3 buckets for web app, images, and documents
3. Create production versions of Lambda functions
4. Create production versions of API keys, passwords, etc.
5. Update secrets with API keys, passwords, etc
6. Deploy production release to production web app bucket

**Comment by ssysoi** [comment]
We need one more bucket since we want to have stage release to test release candidates(it will be used mostly by QA specialists). Currently we have dev bucket with the lastest code(carsnoop-webapp) and  production(carsnoop-webapp-production), which will be used for production(tested releases).  But we need one more bucket to test release candidates(prerelease process), so could you please create it.

**Comment by ssysoi** [comment]
S3 (1) - for development
**S3 (2) - Stable - for (prerelease) - here our QA will test release candidate**
S3 (3) - production (you created)

our architect advice such a solution. it will be reasonable

**Comment by billypilgrim88** [comment]
Done, created carsnoop-webapp-test
