### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#197]
For each scenario, create an entry in the notifications table and then:

1. When a request is submitted, send an email to the seller of each vehicle in the request.
2. When the status of a deal changes, send an email to both buyer and seller.
3. When a chat message is created, send an email to the other chat user that a new message was sent. 
4. When a buyer submits a request to a dealership who has no active users on the CarSnoop platform, send an email to support@carsnoop.com so we can manually reach out to the dealer.
5. When a user registers and joins a dealership with no other users, send an email to support@carsnoop.com with the user's email and phone number so we can manually verify the user actually works at the dealership.

**Comment by k-tratseuski** [comment]
@billypilgrim88 Didn't get the idea with notification table. Why do we need it since we are sending notification via email?
1. To which users should we send the email that request is submitted? Since it could be that dealer has lots of users and we can't use it in a sync way. For that kind of things we need have something async task queue where we could store all our tasks about sending the email, but also we should have some worker that will process all that tasks
2. While creating an offer we could change the status of the main deal, which is accepted, but at the same time we are cancelling and declining other deals that a part of the same request. Should we notify buyer and seller for these declined and cancelled deals?

**Comment by k-tratseuski** [comment]
@TonyaUkrainets Mailings 1,4,5 are ready for testing

**Comment by k-tratseuski** [comment]
@TonyaUkrainets mailing 2 is ready for testing
