### ISSUE TITLE
Email for new message in Chat

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#201]
1. When a chat message is created, send an email to the other chat user that a new message was sent. 
2. Send an email if chat message is "unread".
3. All members of another chat partner`s account should recieve the email.
4. The details in email:
a. car details:
   - year;
   - make;
   - model;
   - trim.
b. last message text preview:
   - max lines are two;
c. link to the transaction`s detailed page.

![image](https://user-images.githubusercontent.com/117083992/220913128-ab33f5e0-646c-4045-97db-5bfbcd353bf1.png)

**Comment by k-tratseuski** [comment]
@scottwoodall, Kristyna described the flow in general. I want to give you more clarifications about more technical things. 
To send email messages I've created new Lambda called `sendEmails`. Which basically reads SQS queue and sends the email based on the message from the queue. We need this approach since we want to send lots of messages and doing it in sync way is not good idea. `sendEmails` renders the pre-created html templates with specific context. From the SQS we receive the list of recepients, template name and context.

So all you need is to create some logic inside chatFunctions that will send the message to the SQS queue with specific format.

Here is the simple example of the logic that sends a message in specific format to the queue:
```python
def send_email(to_email: list, template_name: str, context: dict):
    """Sends message to SQS queue"""
    sqs = boto3.client("sqs")
    sqs.send_message(
        QueueUrl=os.environ["SqsSendEmailsQueue"],
        MessageGroupId=os.environ["SqsSendEmailsGroupId"],
        MessageBody=json.dumps(
            {"to_email": to_email, "template_name": template_name, "context": context}
        ),
    )
``` 

Parameter `template_name` for your case should be `unread_message`
Parameter `context` should have such format:

```python
context = {
    "chat_image": "http://somelink.com",  # link is the same as in readChats for chat, if there is no image should be None since we will show default picture
    "link": f"http://carsnoop-webapp.s3-website.us-east-2.amazonaws.com/contracts/{transaction_id}",  # link to the deal where transaction_id is the id of the transaction
    "vehicle_name": "2020 Honda Odyssey EX",  # year, make, model, trim
    "message_preview": "some test message",  # message preview
}
```

**Comment by k-tratseuski** [comment]
@scottwoodall, Thanks, good job, looks good. Why do you think that these email addresses are invalid, I think that it works perfect and it's exactly what was expected

**Comment by k-tratseuski** [comment]
@scottwoodall got you. But as far as I understand such emails are skipped and not a part of recipients since they are fake. If it's really a problem we could do a cleanup for dev database. For production I think that wouldn't be an issue

**Comment by k-tratseuski** [comment]
@scottwoodall Hmm, seems it's really a problem with fake emails. We need to think what to do with that

**Comment by k-tratseuski** [comment]
@scottwoodall cool, thanks

**Comment by k-tratseuski** [comment]
@scottwoodall Sorry again, but during the tests we've realized that the link could also lead to offer page and we have wrong hostname in that. So we need to build link dynamically. The very first idea that comes to my mind is count contracts with such `transaction_id`. If count >= 1 (we can't have more than one contract in real) the link should contain prefix https://portal-dev.carsnoop.com/contracts/ otherwise it means that we have only the offer https://portal-dev.carsnoop.com/offers/ And I also suggest to move it to envs.
So in the end of the day it should be something like this

```bash
ContractLink=https://portal-dev.carsnoop.com/contracts/
OfferLink=https://portal-dev.carsnoop.com/offers/
```

```python
# Check if the contract was created to build proper link
cursor.execute(
    "SELECT COUNT(1) FROM contracts WHERE transaction_id = %s", (transaction["id"],)
)
if cursor.fetchone()["count"] == 1:
    # If there is some contract - the link should be to it
    link = f"{os.environ['ContractLink']}{transaction_id}"
else:
    # The link to the offer
    link = f"{os.environ['OfferLink']}{transaction_id}"
```

So feel free to change it as you want, I wanted to share my idea.

**Comment by k-tratseuski** [comment]
@scottwoodall check please the latest comment of mine

**Comment by k-tratseuski** [comment]
@scottwoodall thx

**Comment by TonyaUkrainets** [comment]
there are 2 slashes in the link in the letter
the redirect to the deal does not work
![image](https://user-images.githubusercontent.com/112691890/224323703-d15dd7be-60ea-45be-a9ba-47ed71dc622b.png)
