### ISSUE TITLE
createChatMessage returns 502 error

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#207]
Request example:
```
{
    "operation": "createChatMessage",
    "record": {
        "transaction_id": "86869f98-9bb8-443e-bb4c-80969a9da00d",
        "message": "hi"
    }
}
```

**Comment by TonyaUkrainets** [comment]
Please, check for what reason a request is falling with 502 error.
We get an error when sending a message, but despite this a message is sent to the chat.
But we don't expect to get an error on a successful submission.

**Comment by TonyaUkrainets** [comment]
+ readChatMessages does not return link in media_url
![image](https://user-images.githubusercontent.com/112691890/225454423-a35db8b9-2f97-4397-a98d-2227a4d8645e.png)

**Comment by k-tratseuski** [comment]
@scottwoodall I didn't touch anything. Maybe you should ask @billypilgrim88

**Comment by billypilgrim88** [comment]
Did we ever enable CORS for Chats? I don't think we did. I will check.

**Comment by billypilgrim88** [comment]
Can you try it now? I'm not sure CORS ever could have been working because the following mapping was missing in API Gateway:

<img width="730" alt="Screenshot 2023-03-19 at 2 19 39 PM" src="https://user-images.githubusercontent.com/106979142/226198546-6de5c553-a0b4-42dc-be19-f019001b2a87.png">

**Comment by k-tratseuski** [comment]
@billypilgrim88 still having issues

**Comment by billypilgrim88** [comment]
Fixed.

**Comment by billypilgrim88** [comment]
@scottwoodall - the 502 error still appears when calling createChatMessage. The message saves in the database but if fails when trying to send the email. The culprit is in bold below - QueueUrl=os.environ["SqsSendEmailsQueue"] should be changed to reference the secrets value of **sqsSendEmailsQueue**:

[ERROR] KeyError: 'SqsSendEmailsQueue'Traceback (most recent call last):  File "/var/task/lambda_function.py", line 135, in lambda_handler    response = createChatMessage(data)  File "/var/task/lambda_function.py", line 31, in createChatMessage    return carsnoop.communications.send_chat_message(payload)  File "/opt/python/lib/python3.8/site-packages/carsnoop/communications/_send_chat_message/public.py", line 38, in send_chat_message    send_email.deliver()  File "/opt/python/lib/python3.8/site-packages/carsnoop/communications/_send_chat_message/serializers/send_email.py", line 51, in deliver    return services.send_email(  File "/opt/python/lib/python3.8/site-packages/carsnoop/communications/_send_chat_message/services/send_email.py", line 23, in send_email    QueueUrl=os.environ["SqsSendEmailsQueue"],  File "/var/lang/lib/python3.8/os.py", line 675, in __getitem__    raise KeyError(key) from None | [ERROR] KeyError: 'SqsSendEmailsQueue' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 135, in lambda_handler     response = createChatMessage(data)   File "/var/task/lambda_function.py", line 31, in createChatMessage     return carsnoop.communications.send_chat_message(payload)   File "/opt/python/lib/python3.8/site-packages/carsnoop/communications/_send_chat_message/public.py", line 38, in send_chat_message     send_email.deliver()   File "/opt/python/lib/python3.8/site-packages/carsnoop/communications/_send_chat_message/serializers/send_email.py", line 51, in deliver     return services.send_email(   File "/opt/python/lib/python3.8/site-packages/carsnoop/communications/_send_chat_message/services/send_email.py", line 23, in send_email     **QueueUrl=os.environ["SqsSendEmailsQueue"]**,   File "/var/lang/lib/python3.8/os.py", line 675, in __getitem__     raise KeyError(key) from None
-- | --

**Comment by TonyaUkrainets** [comment]
fixed
