### ISSUE TITLE
Seller's Documents Don't Appear to Buyer

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#231]
In production, we have a seller who has uploaded a document for transaction 1214a407-9f9d-4d24-a50f-3fd9e4f53d2d:

<img width="1831" alt="Screenshot 2023-04-13 at 10 28 38 AM" src="https://user-images.githubusercontent.com/106979142/231791848-827f53ce-bda8-46a7-9177-60e90af210e5.png">

However, when the buyer logs in, it shows that this document has not been uploaded yet:

<img width="1824" alt="Screenshot 2023-04-13 at 10 27 11 AM" src="https://user-images.githubusercontent.com/106979142/231792118-c47048bd-c433-4d6b-9d49-8016245b43ff.png">

**Comment by ssysoi** [comment]
we tested in on dev env and it works fine:
![image](https://user-images.githubusercontent.com/56298532/231810772-45456e4d-a2a9-4598-9bec-f4e72dac176b.png)

we need credentials for prod BE for Kostya to find the problem

**Comment by k-tratseuski** [comment]
@billypilgrim88 
I didn't get how is it possible that you have an access to this transaction from both Jon Gilman. Since one of them is a seller, and another one is not a part of buyer's account. There is only one user in buyer account chris@carsnoop.com. I've triggered this endpoint from postman with different session-ids and I see this

When the request is executed as buyer 
![image](https://user-images.githubusercontent.com/117080223/231992255-9330b9e2-a437-4929-86fa-a72054635727.png)
When the request is executed as seller
![image](https://user-images.githubusercontent.com/117080223/231992412-0abfe944-0386-41e8-9fb1-a32cb4eff58e.png)

**Comment by billypilgrim88** [comment]
This does not work on the front end correctly. For the seller, the ID of the loan payoff document is returned:
<img width="2055" alt="Seller View" src="https://user-images.githubusercontent.com/106979142/232571620-01f496cc-7fa8-4382-b7d4-8a28c30f0030.png">

For the buyer, the ID is not returned and thus shows that the document is missing:
<img width="2047" alt="Buyer View" src="https://user-images.githubusercontent.com/106979142/232571706-d0807109-2a7c-4d7e-b962-f438cf79c5b7.png">

**Comment by k-tratseuski** [comment]
Still not clear for me the thing with users. Could you please send me both user ids from readUser endpoint? (you just need to refresh the page for both users and find readUser in the list of requests in Network tab). Or if it's ok send me credentials to these users in email

**Comment by billypilgrim88** [comment]
In the database, you can simply point a user to a different account and refresh the page. I have confirmed with the actual buyer (Indy Honda) that they cannot see the Loan Payoff document.

**Comment by k-tratseuski** [comment]
@billypilgrim88 didn't get you

**Comment by k-tratseuski** [comment]
I see only one user which is seller 
![image](https://user-images.githubusercontent.com/117080223/232825148-afad0367-79c5-4256-8c6a-fc39e7012ccf.png)
![image](https://user-images.githubusercontent.com/117080223/232825198-cb464524-1702-40cc-ad0f-0d958efb2798.png)
The user which is not a part of the seller/buyer account can't read the transaction

**Comment by k-tratseuski** [comment]
For buyer we have 2 users
![image](https://user-images.githubusercontent.com/117080223/232825530-4a516d72-67af-4803-844e-5d1773658b9c.png)
![image](https://user-images.githubusercontent.com/117080223/232825559-a7b2f76b-770b-46a5-9a12-5ea35bcfe6fe.png)

**Comment by k-tratseuski** [comment]
@billypilgrim88 
I with @TonyaUkrainets tested such flows:
1) Create a document by buyer 1 and another document by seller 1
2) These documents are visible for buyer 2 and seller 2
Then we've changed account_id in users's table for another user who wasn't part of any seller/buyer account. Then we've checked that contract and we do see these documents. So the issue is not reproducible for us.

Could you please describe your flow fully with all ids and things that you are changing. Without these things I can't do anything
