### ISSUE TITLE
Subscription payment URL

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#64]
How can we get payment url for subscriptions?

There is a method `updateSubscription` that returns 
```
{
    "name": "Champion Chrysler Dodge Jeep Ram",
    "phone": "+14632050909",
    "stripe_customer": "cus_MrojjAvED67UoP",
    "stripe_payment_method": "pm_1M85GFEZ3w8tMtYcr9IeZEF7",
    "type": "Small",
    "stripe_subscription": "sub_1MEVmvEZ3w8tMtYcSv42vZ4o"
}
```

How should we use this info?

**Comment by jongilman8** [comment]
There is no such thing as a subscription URL, there is only a URL to add a payment method to a dealerships account. updateSubscription works like this:

1. Retrieve the account from the CarSnoop database
2. If the stripe_customer field on the account is blank, call the Stripe API to create the dealership as a customer
3. If the stripe_payment_method field on the account is blank, create a session for the dealership and pass back the URL for the session. The dealership user would then be redirected to the Stipe session to add a payment method and then return to the Subscription screen in the CarSnoop app.
4. If the stripe_subscription field on the account has a value, the backend calls the Stripe API to remove the subscription.
5. If the new subscription is not the Free tier, the backend calls the Stripe API to add the new subscription.

In the scenario where 3 is called, the user will be returned to the CarSnoop app, which means updateSubscription will need to be called again in the background so that 4 and 5 can be executed. This is because a subscription cannot be added to a Stripe customer until a payment method exists on the Stripe customer.
