### ISSUE TITLE
Stripe Webhook to Lock Account on Failed Subscription Payment

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#74]
Need to update the subscription to "Free" if the recurring payment was unsuccessful.

**Comment by billypilgrim88** [comment]
https://stripe.com/docs/webhooks/quickstart?lang=python

**Comment by ssysoi** [comment]
included in https://github.com/CarSnoop-Inc/carsnoop-issues/issues/117

**Comment by billypilgrim88** [comment]
I created the endpoint in Lambda, next I need to trigger a failed payment in Stripe to invoke the webhook. Then I will look at the data and decide how to lock the account in CarSnoop.

**Comment by billypilgrim88** [comment]
Stripe is now configured to invoke the webhook when subscription payments fail. The Lambda endpoint is now being hit. Lastly I need to write some code to update the account and subscription in the CarSnoop database.

**Comment by billypilgrim88** [comment]
Update: this is now complete. We have updated our rules to downgrade the account to the Free subscription after the first failure. This is because Stripe may take several days to attempt the payment again, which means the account could buy and sell more cars in that time without paying for the platform. Now the email will look like this:

CarSnoop
Subscription Payment Failed

Hello Bill Estes Chevrolet,

We attemtped to charge your payment method for your CarSnoop subscription, but it was declined. Your subscription has been downgraded to the Free plan. Please log back in to CarSnoop and upgrade your subscription if you plan to continue to buy and sell cars in the app.

Thank You,

CarSnoop, Inc.
